spring:
  application:
    name: api-gateway
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  cloud:
    gateway:
      server:
        webflux:
          # Descubrimiento automático de servicios
          discovery:
            locator:
              enabled: true # Permite que el gateway use los nombres de Eureka automáticamente
              lower-case-service-id: true # Convierte los IDs de servicio a minúsculas para las rutas
          # Definición de Rutas Explícitas
          routes:
            # RUTA PARA EL IAM SERVICE
            - id: iam-service-route
              # En lugar de poner una IP fija, le pregunta a Eureka quién es `iam-service` y le envía la petición
              # Si tienes 3 instancias de `iam-service` corriendo, Eureka balanceará la carga entre ellas
              uri: lb://iam-service # 'lb://' activa el Load Balancer (balanceador de carga) de Eureka
              predicates:
                - Path=/iam/** # Captura lo que venga como http://localhost:8080/iam/...
              filters:
                - StripPrefix=1 # Elimina '/iam' de la URL antes de enviarla al microservicio